### ISSUE TITLE
No module named best_answer_finder

### ISSUE THREAD

**Issue by Akul2010** [Dipeshpal/Jarvis_AI#18]
Traceback (most recent call last):
  File "C:\Users\materialsworld\anaconda3\lib\site-packages\JarvisAI\__init__.py", line 26, in <module>
    import features.weather.weather as wea
ModuleNotFoundError: No module named 'features'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\materialsworld\Desktop\Akul Goel\Professional Apps\Jarvis\JARVIS\main.py", line 1, in <module>
    import JarvisAI
  File "C:\Users\materialsworld\anaconda3\lib\site-packages\JarvisAI\__init__.py", line 79, in <module>
    from JarvisAI.features.chatbot.jarvis_ai_neural_engine import neural_engine
  File "C:\Users\materialsworld\anaconda3\lib\site-packages\JarvisAI\features\chatbot\jarvis_ai_neural_engine\neural_engine.py", line 3, in <module>
    import best_answer_finder
ModuleNotFoundError: No module named 'best_answer_finder'

how do i fix this
thankyou

**Comment by Dipeshpal** [comment]
check latest version and updated docs
