### ISSUE TITLE
Install JarvisAI pip error

### ISSUE THREAD

**Issue by Slient1802** [Dipeshpal/Jarvis_AI#26]
### **Describe the issues:**
I had installed python 3.10 + 3.11,Pycharm...
Error when I install the Jarvis pip

### **How to Reproduce:**
Steps to reproduce the behavior by text:
1. Install pip: 
```
pip install JarvisAI
```
2. See this error pop up:
```
Collecting JarvisAI
  Using cached JarvisAI-4.2-py3-none-any.whl (2.5 MB)
Collecting shutup
  Using cached shutup-0.2.0-py3-none-any.whl (1.5 kB)
Collecting torch
  Downloading torch-1.13.1-cp310-cp310-win_amd64.whl (162.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 MB 4.2 MB/s eta 0:00:00
Collecting gtts
  Using cached gTTS-2.3.0-py3-none-any.whl (26 kB)
Requirement already satisfied: wikipedia in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (1.4.0)
Requirement already satisfied: pywhatkit in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (5.4)  
Requirement already satisfied: beautifulsoup4 in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (4
.11.1)
Requirement already satisfied: requests in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (2.28.1)
Collecting googlesearch-python
  Using cached googlesearch_python-1.1.0-py3-none-any.whl (3.6 kB)
Requirement already satisfied: pyjokes in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (0.6.0)
Collecting pipwin
  Using cached pipwin-0.5.2.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... done
Collecting playsound==1.2.2
  Using cached playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Collecting fuzzywuzzy
  Using cached fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (1.23.4)   
Collecting lxml
  Using cached lxml-4.9.2-cp310-cp310-win_amd64.whl (3.8 MB)
Requirement already satisfied: SpeechRecognition in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI)
 (3.9.0)
Collecting youtube-search-python
  Using cached youtube_search_python-1.6.6-py3-none-any.whl (89 kB)
Collecting pytube
  Using cached pytube-12.1.2-py3-none-any.whl (57 kB)
Collecting phonetics
  Using cached phonetics-1.0.5.tar.gz (8.8 kB)
  Preparing metadata (setup.py) ... done
Collecting mediapipe==0.8.11
  Using cached mediapipe-0.8.11-cp310-cp310-win_amd64.whl (49.0 MB)
Collecting download
  Using cached download-0.3.5-py3-none-any.whl (8.8 kB)
Collecting pyaudio
  Using cached PyAudio-0.2.13-cp310-cp310-win_amd64.whl (164 kB)
Collecting pyscreenshot
  Using cached pyscreenshot-3.0-py3-none-any.whl (27 kB)
Collecting wave
  Using cached Wave-0.0.2.zip (38 kB)
  Preparing metadata (setup.py) ... done
Collecting opencv-python
  Using cached opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (38.2 MB)
Requirement already satisfied: pyttsx3 in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (2.90)
Collecting spacy
  Using cached spacy-3.4.4-cp310-cp310-win_amd64.whl (11.9 MB)
Requirement already satisfied: Flask in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (from JarvisAI) (2.2.2)
Collecting googletrans
  Using cached googletrans-3.0.0.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting JarvisAI
  Using cached JarvisAI-4.1-py3-none-any.whl (2.5 MB)
  Using cached JarvisAI-4.0-py3-none-any.whl (2.5 MB)
Collecting webrtcvad
  Using cached webrtcvad-2.0.10.tar.gz (66 kB)
  Preparing metadata (setup.py) ... done
Collecting JarvisAI
  Using cached JarvisAI-3.9-py3-none-any.whl (36 kB)
Collecting pipwin==0.5.0
  Using cached pipwin-0.5.0-py2.py3-none-any.whl (7.6 kB)
Collecting shutup==0.1.3
  Using cached shutup-0.1.3-py3-none-any.whl (1.3 kB)
Collecting youtube-search-python==1.5.3
  Using cached youtube_search_python-1.5.3-py3-none-any.whl (73 kB)
Collecting librosa==0.8.0
  Using cached librosa-0.8.0.tar.gz (183 kB)
  Preparing metadata (setup.py) ... done
Collecting transformers==4.3.2
  Using cached transformers-4.3.2-py3-none-any.whl (1.8 MB)
Collecting beautifulsoup4==4.9.3
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting SpeechRecognition==3.8.1
  Using cached SpeechRecognition-3.8.1-py2.py3-none-any.whl (32.8 MB)
Collecting opencv-contrib-python==4.5.2.52
  Using cached opencv-contrib-python-4.5.2.52.tar.gz (149.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [316 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64"' don't match your environment        
      Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "linux" and platform_machine == "aarch64"' don't ma
tch your environment
      Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_machine == "aarch64"' don't m
atch your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64"' don't match your environment        
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64"' don't match your environment        
      Collecting setuptools
        Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting scikit-build
        Downloading scikit_build-0.16.4-py3-none-any.whl (78 kB)
           -------------------------------------- 78.6/78.6 kB 727.3 kB/s eta 0:00:00
      Collecting cmake
        Using cached cmake-3.25.0-py2.py3-none-win_amd64.whl (32.6 MB)
      Collecting pip
        Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
     
        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1
     
        [275 lines of output]
        setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.
          warnings.warn(
        Running from numpy source directory.
        setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding te
mplates
          run_build = parse_setuppy_commands()
        Processing numpy/random\_bounded_integers.pxd.in
        Processing numpy/random\bit_generator.pyx
        Processing numpy/random\mtrand.pyx
        Processing numpy/random\_bounded_integers.pyx.in
        Processing numpy/random\_common.pyx
        Processing numpy/random\_generator.pyx
        Processing numpy/random\_mt19937.pyx
        Processing numpy/random\_pcg64.pyx
        Processing numpy/random\_philox.pyx
        Processing numpy/random\_sfc64.pyx
        Cythonizing sources
        blas_opt_info:
        blas_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anac
onda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        blis_info:
          libraries blis not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anacon
da3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        openblas_info:
          libraries openblas not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\an
aconda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 
'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE
     
        atlas_3_10_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries tatlas not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anac
onda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        atlas_3_10_blas_info:
          libraries satlas not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anac
onda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        atlas_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\U
sers\\Admin\\anaconda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        atlas_blas_info:
          libraries f77blas,cblas,atlas not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users
\\Admin\\anaconda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        accelerate_info:
          NOT AVAILABLE
     
        C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\system_i
nfo.py:1914: UserWarning:
            Optimized (vendor) Blas libraries are not found.
            Falls back to netlib Blas library which has worse performance.
            A better performance should be easily gained by switching
            Blas library.
          if self._calc_info(blas):
        blas_info:
          libraries blas not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anacon
da3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\system_i
nfo.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [blas]) or by setting
            the BLAS environment variable.
          if self._calc_info(blas):
        blas_src_info:
          NOT AVAILABLE
      
        C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\system_i
nfo.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [blas_src]) or by setting
            the BLAS_SRC environment variable.
          if self._calc_info(blas):
          NOT AVAILABLE
     
        non-existing path in 'numpy\\distutils': 'site.cfg'
        lapack_opt_info:
        lapack_mkl_info:
          libraries mkl_rt not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anac
onda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        openblas_lapack_info:
          libraries openblas not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\an
aconda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        openblas_clapack_info:
          libraries openblas,lapack not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Ad
min\\anaconda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        flame_info:
          libraries flame not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anaco
nda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries tatlas,tatlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries lapack_atlas not found in C:\
          libraries tatlas,tatlas not found in C:\
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries tatlas,tatlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\Library\lib
          libraries tatlas,tatlas not found in C:\Users\Admin\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE
     
        atlas_3_10_info:
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries satlas,satlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries lapack_atlas not found in C:\
          libraries satlas,satlas not found in C:\
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries satlas,satlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\Library\lib
          libraries satlas,satlas not found in C:\Users\Admin\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE
     
        atlas_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries lapack_atlas not found in C:\
          libraries ptf77blas,ptcblas,atlas not found in C:\
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\Library\lib
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\Admin\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE
     
        atlas_info:
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries f77blas,cblas,atlas not found in C:\Users\Admin\anaconda3\envs\My_project\lib
          libraries lapack_atlas not found in C:\
          libraries f77blas,cblas,atlas not found in C:\
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries f77blas,cblas,atlas not found in C:\Users\Admin\anaconda3\envs\My_project\libs
          libraries lapack_atlas not found in C:\Users\Admin\anaconda3\Library\lib
          libraries f77blas,cblas,atlas not found in C:\Users\Admin\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE
     
        lapack_info:
          libraries lapack not found in ['C:\\Users\\Admin\\anaconda3\\envs\\My_project\\lib', 'C:\\', 'C:\\Users\\Admin\\anac
onda3\\envs\\My_project\\libs', 'C:\\Users\\Admin\\anaconda3\\Library\\lib']
          NOT AVAILABLE
     
        C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\system_i
nfo.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        lapack_src_info:
          NOT AVAILABLE
     
        C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\system_i
nfo.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
          NOT AVAILABLE
     
        numpy_linalg_lapack_lite:
          FOUND:
            language = c
            define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
     
        C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: 
UserWarning: Unknown distribution option: 'define_macros'
          warnings.warn(msg)
        running dist_info
        running build_src
        build_src
        building py_modules sources
        creating build
        creating build\src.win-amd64-3.10
        creating build\src.win-amd64-3.10\numpy
        creating build\src.win-amd64-3.10\numpy\distutils
        building library "npymath" sources
        Traceback (most recent call last):
          File "C:\Users\Admin\anaconda3\envs\My_project\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line
 351, in <module>
            main()
          File "C:\Users\Admin\anaconda3\envs\My_project\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line
 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Users\Admin\anaconda3\envs\My_project\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line
 152, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\build_meta.py", 
line 157, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\build_meta.py", 
line 248, in run_setup
            super(_BuildMetaLegacyBackend,
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\build_meta.py", 
line 142, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 508, in <module>
            setup_package()
          File "setup.py", line 500, in setup_package
            setup(**metadata)
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
core.py", line 169, in setup
            return old_setup(**new_attr)
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\__init__.py", li
ne 165, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\core.
py", line 148, in setup
            dist.run_commands()
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\dist.
py", line 967, in run_commands
            self.run_command(cmd)
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\dist.
py", line 986, in run_command
            cmd_obj.run()
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\command\dist_inf
o.py", line 31, in run
            egg_info.run()
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\egg_info.py", line 24, in run
            self.run_command("build_src")
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\cmd.p
y", line 313, in run_command
            self.distribution.run_command(command)
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\dist.
py", line 986, in run_command
            cmd_obj.run()
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\build_src.py", line 144, in run
            self.build_sources()
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\build_src.py", line 155, in build_sources
            self.build_library_sources(*libname_info)
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\build_src.py", line 288, in build_library_sources
            sources = self.generate_sources(sources, (lib_name, build_info))
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\build_src.py", line 378, in generate_sources
            source = func(extension, build_dir)
          File "numpy\core\setup.py", line 658, in get_mathlib_info
            st = config_cmd.try_link('int main(void) { return 0;}')
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\comma
nd\config.py", line 243, in try_link
            self._link(body, headers, include_dirs,
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\config.py", line 162, in _link
            return self._wrap_method(old_config._link, lang,
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\config.py", line 96, in _wrap_method
            ret = mth(*((self,)+args))
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\comma
nd\config.py", line 137, in _link
            (src, obj) = self._compile(body, headers, include_dirs, lang)
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\config.py", line 105, in _compile
            src, obj = self._wrap_method(old_config._compile, lang,
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
command\config.py", line 96, in _wrap_method
            ret = mth(*((self,)+args))
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\comma
nd\config.py", line 132, in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\_msvc
compiler.py", line 401, in compile
            self.spawn(args)
          File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-rj_aw3he\overlay\Lib\site-packages\setuptools\_distutils\_msvc
compiler.py", line 505, in spawn
            return super().spawn(cmd, env=env)
          File "C:\Users\Admin\AppData\Local\Temp\pip-install-w_b5kd3_\numpy_04ac7cc3e5884d778a1a420bec7a5697\numpy\distutils\
ccompiler.py", line 90, in <lambda>
            m = lambda self, *args, **kw: func(self, *args, **kw)
        TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
        [end of output]
     
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
     
      Encountered error while generating package metadata.
     
      See above for output.
     
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

### **Expected behavior:**
Install JarvisAI pip

**Comment by Dipeshpal** [comment]
You are having some problem while installing numpy. See in logs-

```
Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64"' don't match your environment        
      Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "linux" and platform_machine == "aarch64"' don't ma
tch your environment
      Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "darwin" and platform_machine == "aarch64"' don't m
atch your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64"' don't match your environment        
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64"' don't match your environment
```

So try numpy in venv seperately and then install JarvisAI. You can also try without using anaconda, I mean use python 3.8 or above itself (original) without conda or anaconda.

**Comment by Slient1802** [comment]
@Dipeshpal hmm that's very weird, because I had install numpy already
```
Requirement already satisfied: numpy in c:\users\admin\anaconda3\envs\my_project\lib\site-packages (1.23.4)
```
and what do you mean by "try without using anaconda"? try to run without venv? or try I have to uninstall the anaconda? or I have to run with python interpreter 3.11 (original)/conda? 
(I'm using Pycharm btw)
